in_channels: 99
learning_rate: [0.001, 0.0001, 0.00001]
max_epochs: [10, 50, 100]
optimizer: ['Adam', 'AdamW', 'SGD']
depth: [2,3,4]
kernel_size: 3
n_encoders: 2
num_workers: 23
model_type: UNet
out_channels: 4